package com.framework.android.allpages;

import org.openqa.selenium.By;

public class KooCreationPage {
	
	public String Chkbox_Select_Language = "//android.widget.TextView[@text=\"###\"]"; 
	public By OTP_btn = By.id("com.koo.app:id/phone_no_next_button");
	public By viewPostedKooButton = By.id("com.koo.app:id/custom_snackbar_action_btn");
	public By selectImage = By.xpath("(//android.view.View[@content-desc=\"media_grid\"])[1]/android.view.View[1]");
	public By nextButton = By.xpath("//android.widget.TextView[@text='Next']");
	public By addImageButton = By.xpath("//android.view.View[@content-desc=\"add_image\"]");
	public By enablePermissionButton = By.xpath("(//android.widget.TextView)[3]");
	public By lbl_OTP = By.id("com.koo.app:id/otp_edit_text");
	public By btn_verify = By.id("com.koo.app:id/button_verify");
	public By tab_feed = By.xpath("(//android.widget.TextView)[1]");
	public By btn_plus = By.xpath("//*[@resource-id='com.koo.app:id/circular_fab_plus'])[2]");
	public By btn_Schedule = By.xpath("//android.widget.ImageView[@content-desc='Back Button']/../android.view.View[1]");
	public By btn_draft = By.xpath("//android.widget.ImageView[@content-desc='Back Button']/../android.view.View[2]");
	public By txt_languages = By.xpath("(//android.view.View)[8]");
	public By btn_no = By.xpath("//android.widget.TextView[@content-desc='negativeButton']");
	public String btn_post = "//android.widget.TextView[@text='###']"; 
	public By txt_Message = By.xpath("//android.widget.EditText");
	public By btn_addlanguage_plus = By.xpath("//android.view.View[@content-desc='add_language']");
	public By checkbox_selectLanguage = By.xpath("(//android.view.View)[14]");
	public By checkbox_selectLanguage1 = By.xpath("//android.widget.TextView[@text='Telugu']");
	public By btn_done_ = By.xpath("//android.widget.Button");
	public String btn_next = "//android.widget.TextView[@text='###']";
	public String txt_preview = "//android.widget.TextView[@text='###']";
	public By txt_profileicon = By.xpath("//android.widget.TextView[@text='Just Now']");
	public By btn_remove = By.xpath("(//android.view.View[@content-desc='koo_create_preview_close'])[2]");
	public By btn_undo = By.xpath("//android.view.View[@content-desc='koo_create_preview_undo']");
	public By btn_add_poll = By.xpath("//android.view.View[@content-desc='add_poll']");
	public By btn_add_image = By.xpath("//android.view.View[@content-desc='add_image']");
	public By btn_add_video = By.xpath("//android.view.View[@content-desc='add_video']");
	public By btn_add_link = By.xpath("//android.view.View[@content-desc='add_link_micro']");
	public By btn_add_speechtotext = By.xpath("//android.view.View[@content-desc='speech_to_text']");
	public By btn_settings = By.xpath("//android.view.View[@content-desc='settings']");
	public By txt_comment_preferences = By.xpath("//android.widget.TextView[@content-desc='comment_preference']");
	public By txt_keyboard_preferences = By.xpath("//android.widget.TextView[@content-desc='keyboard_preference']");
	public String chkbox_everyone = "//android.widget.CheckBox[@content-desc='###']";
	public String chkbox_peopleyoufollow = "//android.widget.CheckBox[@content-desc='###']";
	public String chkbox_noone = "//android.widget.CheckBox[@content-desc='###']";
	public String chkbox_auto_transliteration_keyboard = "//android.widget.CheckBox[@content-desc='###']";
	public String btn_ScheduleKoo = "//android.widget.TextView[@text='###']";
	public By btn_ScheduleKoo2 = By.xpath("(//android.view.View)[4]");
	public String btn_ViewScheduledKoos = "//android.widget.TextView[@text='###']";
	public By btn_ScheduleKoo1 = By.xpath("(//android.widget.Button)[3]");
	public By btn_skipandpost = By.xpath("(//android.widget.Button)[4]");
	public String btn_ScheduleKoomessage = "//android.widget.TextView[@text='###']";
	public By btn_okScheduleKoo = By.xpath("//android.widget.TextView[@content-desc='positiveButton']");
	public String txt_scheduledanddrafts = "//android.widget.TextView[contains(@text,'###')]";
	public String btn_published = "//android.widget.TextView[contains(@text,'###')]";
	public String btn_upcoming = "//android.widget.TextView[contains(@text,'###')]";
	public String btn_draft1 = "//android.widget.TextView[contains(@text,'###')]";
	public By btn_drafts = By.xpath("//android.widget.TextView[@text='Scheduled & Drafts']");
	public By menu_hamberger = By.id("com.koo.app:id/iv_options_more");
	public By btn_editkoo = By.id("com.koo.app:id/itemEditContent");
	public By btn_deletekoo = By.id("com.koo.app:id/itemDeleteContent");
	public By btn_yes = By.id("android:id/button1");
	public String btn_viewdrafts = "//android.widget.TextView[@text='###']";
	public By menu_drafthamberger = By.xpath("(//android.widget.ImageView[@resource-id='com.koo.app:id/iv_options_more'])[1]");
	public String btn_exclusive = "//android.widget.TextView[@text='###']";
	public By btn_exclusive_ok = By.xpath("(//android.widget.TextView)[3]");
	public By txt_postHeader = By.id("com.koo.app:id/channel_name_textview");
	public By btn_shareonWhatsp = By.id("com.koo.app:id/tvWhatsAppStatus");
	public By btn_shareonFacebook = By.id("com.koo.app:id/tvShareFacebook");
	public By everyone_chkbx = By.xpath("//android.widget.CheckBox[@content-desc='Everyone_checkbox_true']");
	public By btn_reKoo = By.id("com.koo.app:id/tv_add_comment_to_this_rekoo");
	public By rekoo_no = By.id("com.koo.app:id/rekooNo");
	public By btn_mlkeditkoo1 = By.xpath("(//android.view.View[@content-desc='koo_create_preview_edit'])[1]");
	public By txt_editText1 = By.xpath("(//android.widget.EditText[@content-desc='koo_create_preview_text'])[1]");
	public By txt_editText2 = By.xpath("(//android.widget.EditText[@content-desc='koo_create_preview_text'])[2]");
	public By btn_dlthmbrgrmenu = By.xpath("(//android.widget.ImageView[@resource-id='com.koo.app:id/iv_options_more'])[1]");
	public By btn_dltkooinfeed = By.id("com.koo.app:id/itemDeleteContent");
	public By txt_dltkoo = By.id("com.koo.app:id/itemDeleteContent");
	public By btn_profile = By.id("com.koo.app:id/clProfile");
	public By btn_yesdltkoo = By.id("android:id/button1");
	public By btn_threadkoo = By.xpath("//android.widget.ImageView[@content-desc='Back Button']/../android.view.View[12]");
	public By txt_errorMsg = By.xpath("//android.widget.TextView[@content-desc='koo_create_textField']");
	public By btn_editProfileClose = By.xpath("//android.view.View[@content-desc='close']");
	public By btn_addGIF = By.xpath("//android.view.View[@content-desc='add_gif']");
	public By btn_addGIFImage = By.xpath("(//android.view.View)[8]");
	public By btn_language2 = By.xpath("(//android.view.View)[14]");
	public By btn_language3 = By.xpath("(//android.view.View)[16]");
	public By btn_language1 = By.xpath("(//android.view.View)[12]");
	public By txt_posted = By.xpath("//android.widget.EditText[@content-desc='koo_create_textField']");
	public By btn_editKoo = By.id("com.koo.app:id/itemEditContent");
	public By txt_editedKoo = By.id("com.koo.app:id/topic_title_textview");
	public By btn_like = By.id("com.koo.app:id/like_imageview");
	public By txt_bftEditTxt = By.xpath("//android.widget.EditText");
	public By txt_threadkoo1 = By.xpath("(//android.widget.TextView[@resource-id='com.koo.app:id/topic_title_textview'])[1]");
	public By txt_threadkoo2 = By.xpath("(//android.widget.TextView[@resource-id='com.koo.app:id/topic_title_textview'])[2]");
	public By btn_backinMLK = By.xpath("//android.widget.ImageView[@content-desc='Back Button']");
	public By first_menu_hamberger = By.xpath("(//*[@resource-id='com.koo.app:id/iv_options_more'])[1]");
	
	public String Chkbox_Select_Language_Name = ""; 
	public String OTP_btn_Name = "";
	public String viewPostedKooButton_Name = "View Koo button from footer bar";
	public String selectImage_Name = "first image from gallery to select";
	public String nextButton_Name = "Next button after selecting picture";
	public String addImageButton_Name = "Add Image Button";
	public String enablePermissionButton_Name = "Enable Permission Button";
	public String lbl_OTP_Name = "";
	public String btn_verify_Name = "";
	public String tab_feed_Name = "";
	public String btn_plus_Name = "Plus Button";
	public String btn_Schedule_Name = "";
	public String btn_draft_Name = "";
	public String txt_languages_Name = "";
	public String btn_no_Name = "";
	public String btn_post_Name = "Post";
	public String txt_Message_Name = "Koo creation text field";
	public String btn_addlanguage_plus_Name = "";
	public String checkbox_selectLanguage_Name = "";
	public String checkbox_selectLanguage1_Name = "";
	public String btn_done__Name = "";
	public String btn_next_Name = "";
	public String txt_preview_Name = "";
	public String txt_profileicon_Name = "";
	public String btn_remove_Name = "";
	public String btn_undo_Name = "";
	public String btn_add_poll_Name = "";
	public String btn_add_image_Name = "";
	public String btn_add_video_Name = "";
	public String btn_add_link_Name = "";
	public String btn_add_speechtotext_Name = "";
	public String btn_settings_Name = "";
	public String txt_comment_preferences_Name = "";
	public String txt_keyboard_preferences_Name = "";
	public String chkbox_everyone_Name = "";
	public String chkbox_peopleyoufollow_Name = "";
	public String chkbox_noone_Name = "";
	public String chkbox_auto_transliteration_keyboard_Name = "";
	public String btn_ScheduleKoo_Name = "";
	public String btn_ScheduleKoo2_Name = "";
	public String btn_ViewScheduledKoos_Name = "";
	public String btn_ScheduleKoo1_Name = "";
	public String btn_skipandpost_Name = "";
	public String btn_ScheduleKoomessage_Name = "";
	public String btn_okScheduleKoo_Name = "ok Yes button";
	public String txt_scheduledanddrafts_Name = "";
	public String btn_published_Name = "";
	public String btn_upcoming_Name = "";
	public String btn_draft1_Name = "";
	public String btn_drafts_Name = "";
	public String menu_hamberger_Name = "";
	public String btn_editkoo_Name = "";
	public String btn_deletekoo_Name = "";
	public String btn_yes_Name = "";
	public String btn_viewdrafts_Name = "";
	public String menu_drafthamberger_Name = "";
	public String btn_exclusive_Name = "";
	public String btn_exclusive_ok_Name = "";
	public String txt_postHeader_Name = "";
	public String btn_shareonWhatsp_Name = "";
	public String btn_shareonFacebook_Name = "";
	public String everyone_chkbx_Name = "";
	public String btn_reKoo_Name = "";
	public String rekoo_no_Name = "";
	public String btn_mlkeditkoo1_Name = "";
	public String txt_editText1_Name = "";
	public String txt_editText2_Name = "";
	public String btn_dlthmbrgrmenu_Name = "";
	public String btn_dltkooinfeed_Name = "";
	public String txt_dltkoo_Name = "";
	public String btn_profile_Name = "";
	public String btn_yesdltkoo_Name = "";
	public String btn_threadkoo_Name = "";
	public String txt_errorMsg_Name = "";
	public String btn_editProfileClose_Name = "";
	public String btn_addGIF_Name = "";
	public String btn_addGIFImage_Name = "";
	public String btn_language2_Name = "";
	public String btn_language3_Name = "";
	public String btn_language1_Name = "";
	public String txt_posted_Name = "";
	public String btn_editKoo_Name = "";
	public String txt_editedKoo_Name = "";
	public String btn_like_Name = "";
	public String txt_bftEditTxt_Name = "";
	public String txt_threadkoo1_Name = "";
	public String txt_threadkoo2_Name = "";
	public String btn_backinMLK_Name = "";
	

}
